#!/usr/bin/env python

from my_rospy_srv_server.srv import *
import rospy

def handle(req):
    resp=MyRospySrvServerResponse()
    resp.c=req.a+req.b
    print "Request {a: %s, b: %s}. Returning response {c: %s}." % (req.a, req.b, resp.c)
    return resp

def main():
    rospy.init_node('my_rospy_srv_server')
    s = rospy.Service('my_rospy_srv_server', MyRospySrvServer, handle)
    print "Ready."
    rospy.spin()

if __name__ == "__main__":
    main()

